### PR TITLE
UCI arguments

### PR DESCRIPTION
**Pull request by ArjunSahlot**
## Describe changes
Argument support.

## Testing info
Works.

### CODE REVIEW

**Comment by HuangPatrick16777216** [comment]
I don't understand what commit b05e9b5 does. It seems like you are adding a lot of computations, i.e. `pos.loc` to `pos.x + (pos.y<<3)`

**Comment by ArjunSahlot** [comment]
That was a mistake, I pressed control z in vscode and it brought me back to some other old branch which wasn't as optimized as the current one.

**Comment by ArjunSahlot** [comment]
The commit has been fixed.

**Comment by HuangPatrick16777216** [comment]
Why did you remove `using std::vector` and `using std::string` on many files? Those are very commonly used classes, and the code looks much cleaner without `std::` in front of every usage.

**Comment by ArjunSahlot** [comment]
I removed using `std::vector` and using `std::string` only in `*.hpp` files and files that weren't using them. The reason I removed them in `.hpp` files is because whenever a `.hpp` file gets included, even the `using` statements are added to the file that included the `.hpp` file. The convention is not to use `using` statements to prevent collisions to where ever it is used.

**Comment by HuangPatrick16777216** [comment]
If you have the same `using` statements on all files, there will be no collisions. Before, all header files had five usings: `cin, cout, endl, vector, string`. The `cpp` files had all of those and some others that were specific to that file. There would be no collisions in that case. Also, the stackoverflow post talks about not doing `using namespace`, which I agree, but we are only using specific members.

**Comment by ArjunSahlot** [comment]
Yes, there wouldn't be any collisions, but that is the convention. Making our code easier to understand for others. Also, the second answer talks about `using` statements in general, and it has a comment which has 3 upvotes and says "you seem to be the only one how understood the actual question...".

**Pull request closed without merging**
