### PR TITLE
Antichess variant

### PR DESCRIPTION
**Pull request by ArjunSahlot**
## Describe changes
Add antichess variant.

## Testing info
Tested 2 games. Plays well but not much work is done on better eval, only evaluates material and win/loss.

### CODE REVIEW

**Comment by HuangPatrick16777216** [comment]
There are [bugs][bug] (antichess ending) and [slow code][slow] (using `startswith`), and [here][slow2]. Use arrays when creating a constant sequence.
Also, many of these commits seem to cancel each other out. If you are going to change something for the convenience of testing, please do not commit it.

[bug]: https://github.com/megalodon-chess/megalodon/pull/74/files#diff-dec0e258861db3253b81160c750bade3b721e27abbf8d07573b56198e540fc5d
[slow]: https://github.com/megalodon-chess/megalodon/pull/74/files#diff-deb2dd9a115612d5a824679a9fea753d5b66d77bfb8d67c01d3be707dab430e7
[slow2]: https://github.com/megalodon-chess/megalodon/pull/74/commits/7c8823f81e893e7ec926742154cdb28cdff878ce#diff-a4c050acb925a30a662c7f8c4ba06da77f99c236f74c04b91b74a453e84d7747

**Comment by ArjunSahlot** [comment]
Antichess ending: I am not sure what the bug is. Could you give more information?
Slow code: I agree, Fixed in [d1dcd2b739e5df2e3ab3aa2eab1acf95b5e8c10](https://github.com/megalodon-chess/megalodon/commit/fd1dcd2b739e5df2e3ab3aa2eab1acf95b5e8c10)
"here": That was changed because we agreed that it would make it unnecessarily more complex.

**Comment by HuangPatrick16777216** [comment]
In your ending, if `white == EMPTY` (all of white's pieces are gone), it returns a black win score. It should be the opposite. Same for black.

**Comment by ArjunSahlot** [comment]
Nice catch, you are right. Fixed in [1a4456d84ee842bc50907d88dab1d05996e4b6fd](https://github.com/megalodon-chess/megalodon/commit/1a4456d84ee842bc50907d88dab1d05996e4b6fd)

**Pull request closed without merging**
